[project]
name = "physics-sims"
version = "0.1.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/Wmbat/physics-sims/"
git_default_branch = "main"

[paths]
output_dir = "docs/"
compile_commands = "compile_commands.json"

[ignore]
ignore_private_members = true
